spring.application.name=springweblearning

logging.level.org.springframework.boot.autoconfigure=DEBUG
debug=true

#spring.datasource.url=jdbc:h2:mem:testdb

#for defining persistent h2 db instead of in-memory

spring.h2.console.path=/h2-console
spring.h2.console.enabled=true

spring.datasource.url=jdbc:h2:file:C:/Users/viren/OneDrive/Documents/springWebLearning/db
#spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username = virendra
spring.datasource.password = 123454321

#spring.jpa.hibernate.ddl-auto=update
